config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  resources :farms, only: [ :show ] do
    resources :calendrier, controller: 'events', only: [ :index, :edit, :update, :new, :create, :destroy ]
    post "events_multiple_update", to: 'events#events_multiple_update'

    resources :produits, controller: 'products', only: [ :index, :show, :edit, :update, :create, :new ]
    resources :daily_egg_counts, only: [ :index, :show, :edit, :update, :create, :new, :destroy ]
    resources :variets, controller: 'vegetable_variets', only: [ :edit, :update, :create, :new ]
    get "product_variets_multiple_new", to: 'products#product_variets_multiple_new'
    post "product_variets_multiple_create", to: 'products#product_variets_multiple_create'
    resources :plandeculture, controller: 'crop_plan_lines', only: [ :index, :update, :edit ]
    resources :crop_plan_line_events, only: [ :update ]
    resources :newsletter_subscribers, only: [ :index, :new, :create ]
    resources :crop_plan_line_user_events, only: [ :create, :update, :destroy ]
    resources :ventes, controller: 'sales', only: [ :index, :show ]
    resources :poulettes, controller: 'hen_actions', only: [ :index, :show, :new, :create, :destroy, :edit, :update ]
    resources :decisions, only: [ :index, :show, :new, :create, :destroy, :edit, :update ]
    resources :pointsdevente, controller: 'outlets', only: [ :index, :show, :new, :create, :edit, :update ] do
      resources :baskets, only: [ :new, :create ]
      resources :factures, controller: "invoices", only: [ :new, :create, :index, :show, :update, :destroy ]
      resources :paiements, controller: "payments", only: [ :new, :create, :index, :show, :update, :destroy ]
      resources :sales, only: [ :index, :show, :new, :create, :update, :destroy ] do
        resources :livraisons, controller: "delivery_slips", only: [ :new, :create, :index, :show, :update, :destroy ]
        resources :baskets, only: [ :index, :show, :update, :destroy ] do
          resources :basket_lines, only: [ :index, :show, :new, :update, :create, :destroy ]
        end
      end
    end
    resources :thebest, controller: 'users', only: [ :show ]
    resources :sales_lines, only: [ :index, :show, :new, :update, :create, :destroy ]
    get "last_prices_multiple_new", to: 'outlets#last_prices_multiple_new'
    post "last_prices_multiple_create", to: 'outlets#last_prices_multiple_create'
    resources :user_events, only: [ :create, :update, :destroy ]
    get 'dashboard', to: 'pages#dashboard'
  end
end

app/models/farm.rb
class Farm < ApplicationRecord
  has_many :users
  has_many :products
  has_many :gardens
  has_many :events
  has_many :outlets
  has_many :hen_actions
  has_many :sales, through: :outlets

  def workers
    self.users.where(worker: true).map{ |worker| worker }.sort_by(&:first_name)[1..-1]
  end

  def clients
    self.users.where(worker: false).map{ |worker| worker }
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show]

  def show
    authorize @farm
    @clients = @farm.clients
    @workers = @farm.workers
    @outlets = @farm.outlets
    @subscribers = NewsletterSubscriber.all.sample(5)
  end

  def set_farm
    @farm = Farm.find(params[:id])
  end
end

app/views/farms/show.html.erb
<div class="container mt-4 custom-container">
  <div class="page-header non-scrolled-page-header scrollable-page-header d-flex justify-content-between">
    <h2>Les Jardins détaillés <span class="ml-2">✨</span></h2>
    <div class="pr-38 d-flex">
      <div class="d-flex justify-content-end mb-4">
    <div class="d-flex">
      <% @workers.each do |worker| %>
        <%= link_to farm_thebest_path(@farm, worker) do  %>
          <div class="d-flex pr-1 pointer">
            <div class="txt-avatar ml-2 <%= worker.color %>">
              <%= worker.initial %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
      <div class="dropdown show ml-4">
        <div class="round-button green" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-plus round-txt-button"></i></div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to new_farm_pointsdevente_path(current_user.farm_id), class: 'white dropdown-item' do %>
            Créer un point de vente
          <% end %>
          <div class="dropdown-farm-create dropleft"><a class="dropdown-item dropdown-toggle" href="#">Créer une vente</a>
            <ul class="submenu dropdown-menu">
              <% @outlets.each do |outlet| %>
                <li><%= link_to new_farm_pointsdevente_sale_path(@farm, outlet), class: 'white dropdown-item' do %><%= outlet.full_name %><% end %></li>
              <% end %>
            </ul>
          </div>
          <%= link_to new_farm_pointsdevente_path(current_user.farm_id), class: 'white dropdown-item' do %>
            Créer une facture
          <% end %>
        </div>
      </div>
    </div>

  </div>

  <div class="page-content">
  </div>
<!--     <div class="d-flex">
      <div></div>
      <div class="progress" data-percentage="0">
          <span class="progress-left">
            <span class="progress-bar"></span>
          </span>
          <span class="progress-right">
            <span class="progress-bar"></span>
          </span>
          <div class="progress-value">
            <div>
              0 %<br>
              <span>du prévi</span>
            </div>
          </div>
        </div>
      </div>
    </div> -->

  <!-- <div class="farm-actions">
      <div></div>
  </div> -->
  <!-- <div class="mt-4">
    <h3>Infos de la ferme</h3>
    <div>
      <%= @farm.full_name %>
    </div>
    <div>
      <%= @farm.address %>
    </div>
    <div>
      <%= @farm.zip_code %>
      <%= @farm.city %>
    </div>
  </div> -->

  <!-- <h3 class="mt-4">Clients directs de la ferme</h3>
  <% @clients.each do |client| %>
    <div>
      <div>
        <%= link_to farm_thebest_path(@farm, client) do  %>
          <span class="raisin"><%= client.first_name %> <%= client.last_name %> <%= client.phone_number ? "-" : "" %> <%= client.phone_number %></span>
        <% end %>
      </div>
    </div>
  <% end %> -->


  <h3 class="mt-4">Quelques groupies</h3>
  <% @subscribers.each do |subscriber| %>
    <div>
      <div>
        <span class="raisin"><%= subscriber.first_name %> <%= subscriber.email %></span>
      </div>
    </div>
  <% end %>
  <div><%= link_to farm_newsletter_subscribers_path(@farm) do %>Voir tout le fan club<% end %></div>

  <div class="w-48-desktop mt-4">
    <div class="dashboard-crop-plan-line-card orange">
      <div class="card-colored-top-part-fixed-color orange">
        <div class="card-top-part-text">Les points de vente</div>
      </div>
      <div class="card-bottom-part">
        <div class="card-bottom-part-text">
          <div class="mt-2 pointer">
            <ul>
              <% @outlets.each do |outlet| %>
              <li>
                <% if outlet.photo.attached? %>
                <%= cl_image_tag outlet.photo.key %>
                <% end %>
                <%= link_to farm_pointsdevente_path(@farm, outlet.id) do %>
                  <%= outlet.full_name %>
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="d-flex justify-content-end card-bottom-section-with-icon">
          <div class="card-bottom-right-triangle orange">
            <%= link_to new_farm_pointsdevente_path(current_user.farm_id), class: 'white' do %>
              <i class="fas fa-plus"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>