config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  resources :farms, only: [ :show ] do
    resources :calendrier, controller: 'events', only: [ :index, :edit, :update, :new, :create, :destroy ]
    post "events_multiple_update", to: 'events#events_multiple_update'

    resources :produits, controller: 'products', only: [ :index, :show, :edit, :update, :create, :new ]
    resources :daily_egg_counts, only: [ :index, :show, :edit, :update, :create, :new, :destroy ]
    resources :variets, controller: 'vegetable_variets', only: [ :edit, :update, :create, :new ]
    get "product_variets_multiple_new", to: 'products#product_variets_multiple_new'
    post "product_variets_multiple_create", to: 'products#product_variets_multiple_create'
    resources :plandeculture, controller: 'crop_plan_lines', only: [ :index, :update, :edit ]
    resources :crop_plan_line_events, only: [ :update ]
    resources :newsletter_subscribers, only: [ :index, :new, :create ]
    resources :crop_plan_line_user_events, only: [ :create, :update, :destroy ]
    resources :ventes, controller: 'sales', only: [ :index, :show ]
    resources :poulettes, controller: 'hen_actions', only: [ :index, :show, :new, :create, :destroy, :edit, :update ]
    resources :decisions, only: [ :index, :show, :new, :create, :destroy, :edit, :update ]
    resources :pointsdevente, controller: 'outlets', only: [ :index, :show, :new, :create, :edit, :update ] do
      resources :baskets, only: [ :new, :create ]
      resources :factures, controller: "invoices", only: [ :new, :create, :index, :show, :update, :destroy ]
      resources :paiements, controller: "payments", only: [ :new, :create, :index, :show, :update, :destroy ]
      resources :sales, only: [ :index, :show, :new, :create, :update, :destroy ] do
        resources :livraisons, controller: "delivery_slips", only: [ :new, :create, :index, :show, :update, :destroy ]
        resources :baskets, only: [ :index, :show, :update, :destroy ] do
          resources :basket_lines, only: [ :index, :show, :new, :update, :create, :destroy ]
        end
      end
    end
    resources :thebest, controller: 'users', only: [ :show ]
    resources :sales_lines, only: [ :index, :show, :new, :update, :create, :destroy ]
    get "last_prices_multiple_new", to: 'outlets#last_prices_multiple_new'
    post "last_prices_multiple_create", to: 'outlets#last_prices_multiple_create'
    resources :user_events, only: [ :create, :update, :destroy ]
    get 'dashboard', to: 'pages#dashboard'
  end
end

app/views/pages/dashboard_sections/_admin_events.html.erb
<div class="dashboard-crop-plan-line-card dashboard-admin-event-card orange" id="decharge-mentale">
  <div class="card-colored-top-part-fixed-color orange">
    <div class="card-top-part-text">Décharge mentale</div>
  </div>
  <div class="card-bottom-part">
    <div class="card-bottom-part-text scrollable-card">
      <div class="mt-2">
        <% if admin_events.empty? %>
        <p><%= "Non, rien de rien..."  %></p>
        <% end %>
        <%= render "pages/dashboard_sections/done_todo_admin_events", farm: farm, admin_events: todo_admin_events, workers: workers, event: event %>
        <%= link_to farm_events_multiple_update_path(farm, start_date: params[:start_date]), method: :post do %>Décaler tout à la semaine pro<% end %>

        <% if !done_admin_events.empty? %>
          <a class="collapsed" data-toggle="collapse" href="#collapse-done-admin-<%= params[:start_date] %>" aria-expanded="false" aria-controls="collapse-done-admin-<%= params[:start_date] %>">
            <div class="d-flex"><h5><p class="mt-4">Déjà fait ! 💪🏻</p></h5><i class="fa" aria-hidden="true"></i></div>
          </a>
          <div class="collapse" id="collapse-done-admin-<%= params[:start_date] %>">
            <%= render "pages/dashboard_sections/done_todo_admin_events", farm: farm, admin_events: done_admin_events, workers: workers, event: event %>
          </div>
        <% end %>

      </div>
    </div>
    <div class="d-flex justify-content-end card-bottom-section-with-icon" id="new-admin-event">
      <a href="#" data-toggle="modal" data-target="#modal-new-admin-event">
        <div class="card-bottom-right-triangle orange">
          <i class="fas fa-plus"></i>
        </div>
      </a>
    </div>
    <%= render "pages/dashboard/create_admin_event_modal", farm: farm, event: @new_event %>
  </div>
</div>

app/views/pages/dashboard_sections/_crop_plan_line_events.html.erb
<div class="mb-4 mb-sm-0 dashboard-crop-plan-line-card green w-48-desktop">
  <div class="card-colored-top-part-fixed-color green">
    <div class="card-top-part-text">From the plan de culture</div>
  </div>
  <div class="card-bottom-part">
    <div class="card-bottom-part-text">
      <div class="mt-3">
        <% if !week_planting.empty? %>
          <h3>Plantation et semis directs</h3>
        <% end %>
        <% week_planting.each do |planting_event| %>
          <div class="d-flex justify-content-between card-list-item-block">
            <div class="card-list-item-left-block">
              <div class="desktop_only">
                <%= link_to farm_crop_plan_line_event_path(farm, planting_event, event_done: true, start_date: params[:start_date]), method: :patch do %>
                  <div class="round-button <%= planting_event.is_done? ? 'olive' : 'green' %> m-2">
                    <i class="fas fa-check round-txt-button"></i>
                  </div>
                <% end %>
              </div>
              <div class="card-list-item-main-info-block">
                <div>


                  <p><%= planting_event.crop_plan_line.has_variet? ? planting_event.crop_plan_line.product.name.capitalize + " - " + planting_event.crop_plan_line.vegetable_variet.name.capitalize : planting_event.crop_plan_line.product.name.capitalize %></p>
                  <p><%= planting_event.seedling_surface %></p>
                </div>
                <div class="card-list-item-second-line"><%= planting_event.bed.garden.name %> - <%= planting_event.bed.name %></div>
              </div>
            </div>
            <div class="d-flex justify-content-between card-list-item-round-button-block">
              <div>
                <%= link_to farm_crop_plan_line_event_path(farm, planting_event, event_done: true, start_date: params[:start_date]), method: :patch do %>
                  <div class="round-button <%= planting_event.is_done? ? 'olive' : 'green' %> mobile_only m-2">
                    <i class="fas fa-check round-txt-button"></i>
                  </div>
                <% end %>
              </div>
              <div class="d-flex">
                <div class="round-button green m-2" data-drawer-trigger aria-controls="drawer-info-cple-<%= planting_event.id %>" aria-expanded="false">
                  <i class="fas fa-search round-txt-button"></i>
                </div>
                <% if planting_event.has_comment? || planting_event.crop_plan_line.has_comment? %>
                  <div class="round-button green m-2" data-drawer-trigger aria-controls="drawer-comment-cple-<%= planting_event.id %>" aria-expanded="false">
                    <i class="fas fa-comment round-txt-button"></i>
                  </div>
                <% else %>
                  <div class="round-button lightgrey m-2" data-drawer-trigger aria-controls="drawer-comment-cple-<%= planting_event.id %>" aria-expanded="false">
                    <i class="fas fa-comment round-txt-button"></i>
                  </div>
                <% end %>
                <%= link_to farm_crop_plan_line_event_path(farm, planting_event, postpone: true, start_date: params[:start_date]), method: :patch do %>
                  <div class="round-button orange m-2">
                    <i class="fas fa-redo-alt round-txt-button"></i>
                  </div>
                <% end %>
              </div>


              <div class="user-button-event">
                <% if planting_event.has_users? %>
                  <div class="dropleft">
                    <div class="dropdown-toggle <%= 'd-flex justify-content-end' if planting_event.has_multiple_users? %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <% planting_event.users.each do |user| %>
                        <div class="d-flex justify-content-end <%= 'ml-minus-24' if planting_event.has_multiple_users? %>">
                          <div class="txt-avatar m-2 pointer <%= user.color %>"><%= user.initial %></div>
                        </div>
                      <% end %>
                    </div>
                    <div class="dropdown-menu">
                      <div class="d-flex">
                        <% workers.each do |worker| %>
                          <% if planting_event.is_user?(worker) %>
                            <%= link_to farm_crop_plan_line_user_event_path(farm, planting_event.user_event(worker.id), start_date: params[:start_date]), :method => :delete do %>
                              <div class="d-flex pr-1 pointer">
                                <div class="txt-avatar m-2 <%= worker.color %>">
                                  <%= worker.initial %>
                                  <div class="delete-user">x</div>
                                </div>
                              </div>
                            <% end %>
                          <% else %>
                            <%= link_to farm_crop_plan_line_user_events_path(event: planting_event, worker: worker.id, start_date: params[:start_date]), :method => :post do %>
                              <div class="d-flex pr-1 pointer">
                                <div class="txt-avatar m-2 <%= worker.color %>">
                                  <%= worker.initial %>
                                </div>
                              </div>
                            <% end %>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% else %>
                  <div class="dropleft">
                    <div class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <div class="d-flex justify-content-end">
                        <div class="round-button green m-2">
                          <i class="fas fa-user-plus round-txt-button"></i>
                        </div>
                      </div>
                    </div>
                    <div class="dropdown-menu">
                      <div class="d-flex">
                        <% workers.each do |worker| %>
                          <%= link_to farm_crop_plan_line_user_events_path(event: planting_event, worker: worker.id, start_date: params[:start_date]), :method => :post do %>
                            <div class="d-flex pr-1 pointer">
                              <div class="txt-avatar m-2 <%= worker.color %>">
                                <%= worker.initial %>
                              </div>
                            </div>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>

            </div>
          </div>
          <!-- drawer commentaire -->
          <%= render "pages/dashboard_drawers/drawer_comment_crop_plan_line_event", cple: planting_event, farm: @farm %>

          <!-- drawer edit comment -->
          <%= render "pages/dashboard_drawers/drawer_edit_comment_crop_plan_line", cple: planting_event, farm: @farm %>

          <!-- drawer new comment -->
          <%= render "pages/dashboard_drawers/drawer_add_comment_crop_plan_line", cple: planting_event, farm: @farm %>
          <!-- drawer info -->
          <%= render "pages/dashboard_drawers/drawer_info_cple", cple: planting_event, farm: @farm %>

        <% end %>

        <!-- <div class="mt-3">
          <h3>Semis en pépinière</h3>
          <div class="d-flex justify-content-between card-list-item-block">
            <div class="card-list-item-left-block">
              <div class="desktop_only">
                <div class="round-button green m-2">
                  <i class="fas fa-check round-txt-button"></i>
                </div>
              </div>
              <div class="card-list-item-main-info-block">
                <div>
                  <p>Courge</p>
                </div>
                <div class="card-list-item-second-line">100 godets | 2 graines par godet</div>
              </div>
            </div>
            <div class="d-flex justify-content-between card-list-item-round-button-block">
              <div>
                <div class="round-button green mobile_only m-2">
                  <i class="fas fa-check round-txt-button"></i>
                </div>
              </div>
              <div class="d-flex">
                <div class="round-button lightgrey m-2">
                  <i class="fas fa-comment round-txt-button"></i>
                </div>
                <div class="round-button orange m-2">
                  <i class="fas fa-redo-alt round-txt-button"></i>
                </div>
              </div>
              <div>
                <div class="txt-avatar olive m-2"><%= current_user.initial %></div>
              </div>
            </div>
          </div>
        </div> -->
        <div class="mt-3">
          <% if !week_bed_preparation_2_weeks.empty? || !week_bed_preparation_1_week.empty? %>
            <h3>Préparation planche</h3>
          <% end %>

          <% if !week_bed_preparation_1_week.empty? %>
            <a class="collapsable-garden-name" data-toggle="collapse" href="#collapse-next-week-<%= params[:start_date] %>" aria-expanded="false" aria-controls="collapse-next-week-<%= params[:start_date] %>">
              <div class="d-flex"><h5>Pour plantation la semaine pro</h5><i class="fa" aria-hidden="true"></i></div>
            </a>
            <div class="collapse show" id="collapse-next-week-<%= params[:start_date] %>">
              <%= render 'pages/dashboard_sections/crop_plan_line_preparation_events', week_bed_preparation_weeks: week_bed_preparation_1_week, farm: @farm, workers: workers %>
            </div>
          <% end %>


          <% if !week_bed_preparation_2_weeks.empty? %>
            <a class="collapsable-garden-name collapsed" data-toggle="collapse" href="#collapse-two-weeks-<%= params[:start_date] %>" aria-expanded="false" aria-controls="collapse-two-weeks-<%= params[:start_date] %>">
              <div class="d-flex mt-2"><h5>Pour plantation dans deux semaines</h5><i class="fa" aria-hidden="true"></i></div>
            </a>
            <div class="collapse" id="collapse-two-weeks-<%= params[:start_date] %>">
              <%= render 'pages/dashboard_sections/crop_plan_line_preparation_events', week_bed_preparation_weeks: week_bed_preparation_2_weeks, farm: @farm, workers: workers %>
            </div>
          <% end %>

        </div>


        <div class="mt-3">
          <% if !week_harvesting.empty? %>
            <h3>Dispo pour la récolte cette semaine</h3>
          <% end %>
          <div class="d-flex flex-wrap justify-content-center">
            <% week_harvesting.each do |harvesting| %>
            <div class="d-flex px-sm-2 px-1">
              <div class="d-flex">
                <div class="align-self-center">
                  <p><%= harvesting.product.name.capitalize %> | </p>
                </div>
                <div class="card-list-item-second-line align-self-center"> <%= harvesting.bed.garden.name %> - <%= harvesting.bed.name %></div>
              </div>
              <% if params[:start_date] && (week_harvesting[0].harvest_start_date.strftime("%W") == (params[:start_date].to_date.strftime("%W")))  %>
                <%= link_to farm_plandeculture_path(farm, harvesting, postpone: true, start_date: params[:start_date], harvesting: true), method: :patch do %>
                  <div class="round-button orange m-sm-2 m-1">
                    <i class="fas fa-redo-alt round-txt-button"></i>
                  </div>
                <% end %>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div id="decharge-mentale-anchor" class="d-flex justify-content-end card-bottom-section-with-icon">
      <%= link_to farm_plandeculture_index_path(current_user.farm_id) do %>
        <div class="card-bottom-right-triangle green">
          <i class="fas fa-seedling" style="padding: 3px 0;"></i>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboard_sections/_crop_plan_line_preparation_events.html.erb
<% week_bed_preparation_weeks.each do |preparing_event| %>
  <div class="d-flex justify-content-between card-list-item-block">
    <div class="card-list-item-left-block">
      <div class="desktop_only">
        <%= link_to farm_crop_plan_line_event_path(farm, preparing_event, event_done: true, start_date: params[:start_date]), method: :patch do %>
          <div class="round-button green <%= preparing_event.is_done? ? 'olive' : 'green' %> m-2">
            <i class="fas fa-check round-txt-button"></i>
          </div>
        <% end %>
      </div>
      <div class="card-list-item-main-info-block">
        <div>
          <p><%= preparing_event.bed.garden.name %> - <%= preparing_event.bed.name %></p>
        </div>
        <div class="card-list-item-second-line"><%= preparing_event.product.name.capitalize %></div>
        <div class="card-list-item-second-line"><!-- 700g Patenkali - 2kg Bioguanor --></div>
      </div>
    </div>
    <div class="d-flex justify-content-between card-list-item-round-button-block">
      <div>
        <%= link_to farm_crop_plan_line_event_path(farm, preparing_event, event_done: true, start_date: params[:start_date]), method: :patch do %>
          <div class="round-button <%= preparing_event.is_done? ? 'olive' : 'green' %> mobile_only m-2">
            <i class="fas fa-check round-txt-button"></i>
          </div>
        <% end %>
      </div>
      <div class="d-flex">
        <div class="round-button green m-2" data-drawer-trigger aria-controls="drawer-info-cple-<%= preparing_event.id %>" aria-expanded="false">
          <i class="fas fa-search round-txt-button"></i>
        </div>
        <% if preparing_event.has_comment? || preparing_event.crop_plan_line.has_comment?  %>
          <div class="round-button green m-2" data-drawer-trigger aria-controls="drawer-comment-cple-<%= preparing_event.id %>" aria-expanded="false">
            <i class="fas fa-comment round-txt-button"></i>
          </div>
        <% else %>
          <div class="round-button lightgrey m-2" data-drawer-trigger aria-controls="drawer-comment-cple-<%= preparing_event.id %>" aria-expanded="false">
            <i class="fas fa-comment round-txt-button"></i>
          </div>
        <% end %>
        <!-- POSTPONE postpone -->
        <%= link_to farm_crop_plan_line_event_path(farm, preparing_event, postpone: true, start_date: params[:start_date], preparing: true), method: :patch do %>
          <div class="round-button orange m-2">
            <i class="fas fa-redo-alt round-txt-button"></i>
          </div>
        <% end %>
      </div>
      <div class="user-button-event">
        <% if preparing_event.has_users? %>
          <div class="dropleft">
            <div class="dropdown-toggle <%= 'd-flex justify-content-end' if preparing_event.has_multiple_users? %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% preparing_event.users.each do |user| %>
                <div class="d-flex justify-content-end <%= 'ml-minus-24' if preparing_event.has_multiple_users? %>">
                  <div class="txt-avatar m-2 pointer <%= user.color %>"><%= user.initial %></div>
                </div>
              <% end %>
            </div>
            <div class="dropdown-menu">
              <div class="d-flex">
                <% workers.each do |worker| %>
                  <% if preparing_event.is_user?(worker) %>
                    <%= link_to farm_crop_plan_line_user_event_path(farm, preparing_event.user_event(worker.id), start_date: params[:start_date]), :method => :delete do %>
                      <div class="d-flex pr-1 pointer">
                        <div class="txt-avatar m-2 <%= worker.color %>">
                          <%= worker.initial %>
                          <div class="delete-user">x</div>
                        </div>
                      </div>
                    <% end %>
                  <% else %>
                    <%= link_to farm_crop_plan_line_user_events_path(event: preparing_event, worker: worker.id, start_date: params[:start_date]), :method => :post do %>
                      <div class="d-flex pr-1 pointer">
                        <div class="txt-avatar m-2 <%= worker.color %>">
                          <%= worker.initial %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="dropleft">
            <div class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="d-flex justify-content-end">
                <div class="round-button green m-2">
                  <i class="fas fa-user-plus round-txt-button"></i>
                </div>
              </div>
            </div>
            <div class="dropdown-menu">
              <div class="d-flex">
                <% workers.each do |worker| %>
                  <%= link_to farm_crop_plan_line_user_events_path(event: preparing_event, worker: worker.id, start_date: params[:start_date]), :method => :post do %>
                    <div class="d-flex pr-1 pointer">
                      <div class="txt-avatar m-2 <%= worker.color %>">
                        <%= worker.initial %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <!-- drawer commentaire -->

  <%= render "pages/dashboard_drawers/drawer_comment_crop_plan_line_event", cple: preparing_event, farm: farm %>
<!-- drawer edit comment -->
<%= render "pages/dashboard_drawers/drawer_edit_comment_crop_plan_line", cple: preparing_event, farm: farm %>

  <!-- drawer new comment -->
  <%= render "pages/dashboard_drawers/drawer_add_comment_crop_plan_line", cple: preparing_event, farm: farm %>
  <!-- drawer info -->
  <%= render "pages/dashboard_drawers/drawer_info_cple", cple: preparing_event, farm: farm %>

<% end %>

app/views/pages/dashboard_sections/_done_todo_admin_events.html.erb
<% admin_events.each do |admin_event| %>

  <div class="d-flex justify-content-between card-list-item-block" id="admin-event-<%= admin_event.id %>">
    <div class="card-list-item-left-block">
      <div class="desktop_only">
        <%= link_to farm_calendrier_path(farm, admin_event, event_done: true, start_date: params[:start_date]), method: :patch do %>
          <div class="round-button <%= admin_event.is_done? ? 'olive' : 'green' %> m-2">
            <i class="fas fa-check round-txt-button"></i>
          </div>
        <% end %>
      </div>
      <div class="card-list-item-main-info-block">
        <p><%= admin_event.description %></p>
      </div>
    </div>
    <div class="d-flex justify-content-between card-list-item-round-button-block">
      <div class="mobile_only">
        <%= link_to farm_calendrier_path(farm, admin_event, event_done: true, start_date: params[:start_date]), method: :patch do %>
          <div class="round-button green <%= admin_event.is_done? ? 'olive' : 'green' %> m-2">
            <i class="fas fa-check round-txt-button"></i>
          </div>
        <% end %>
      </div>
      <div class="d-flex">
        <div class="round-button green m-2" data-drawer-trigger aria-controls="drawer-info-admin-event-<%= admin_event.id %>" aria-expanded="false">
          <i class="fas fa-search round-txt-button"></i>
        </div>
        <div class="round-button <%= admin_event.has_comment? ? 'green' : 'lightgrey' %> m-2" data-drawer-trigger aria-controls="drawer-tour-des-jardins-comment-<%= admin_event.id %>" aria-expanded="false">
          <i class="fas fa-comment round-txt-button"></i>
        </div>
        <!--            <div class="round-button orange m-2" data-drawer-trigger aria-controls="drawer-tour-des-jardins-edit-<%= admin_event.id %>" aria-expanded="false">
          <i class="fas fa-pen round-txt-button"></i>
        </div> -->
        <%= link_to farm_calendrier_path(farm, admin_event.id, postpone: true, start_date: params[:start_date]), method: :put do %>
          <div class="round-button orange m-2">
            <i class="fas fa-redo-alt round-txt-button"></i>
          </div>
        <% end %>
      </div>
      <div class="user-button-event">
        <% if admin_event.has_users? %>
          <div class="dropleft">
            <div class="dropdown-toggle <%= 'd-flex justify-content-end' if admin_event.has_multiple_users? %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% admin_event.users.each do |user| %>
                <div class="d-flex justify-content-end <%= 'ml-minus-24' if admin_event.has_multiple_users? %>">
                  <div class="txt-avatar m-2 pointer <%= user.color %>"><%= user.initial %></div>
                </div>
              <% end %>
            </div>
            <div class="dropdown-menu">
              <div class="d-flex">
                <% workers.each do |worker| %>
                  <% if admin_event.is_user?(worker) %>
                    <%= link_to farm_user_event_path(farm, admin_event.user_event(worker.id), start_date: params[:start_date]), :method => :delete do %>
                      <div class="d-flex pr-1 pointer">
                        <div class="txt-avatar m-2 <%= worker.color %>">
                          <%= worker.initial %>
                          <div class="delete-user">x</div>
                        </div>
                      </div>
                    <% end %>
                  <% else %>
                    <%= link_to farm_user_events_path(event: admin_event, worker: worker.id, start_date: params[:start_date]), :method => :post do %>
                      <div class="d-flex pr-1 pointer">
                        <div class="txt-avatar m-2 <%= worker.color %>">
                          <%= worker.initial %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="dropleft">
            <div class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="d-flex justify-content-end">
                <div class="round-button green m-2">
                  <i class="fas fa-user-plus round-txt-button"></i>
                </div>
              </div>
            </div>
            <div class="dropdown-menu">
              <div class="d-flex">
                <% workers.each do |worker| %>
                  <%= link_to farm_user_events_path(event: admin_event, worker: worker.id, start_date: params[:start_date]), :method => :post do %>
                    <div class="d-flex pr-1 pointer">
                      <div class="txt-avatar m-2 <%= worker.color %>">
                        <%= worker.initial %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>


  <!-- drawer comment admin event -->
  <%= render "pages/dashboard_drawers/drawer_comment_admin_event", admin_event_id: admin_event.id, admin_event_description: admin_event.description, admin_event_details: admin_event.details, admin_event_comment: admin_event.comment %>


  <!-- À AJOUTER À LA CLASSE DRAWER SI ON VEUT QUE LE DRAWER SOIT OUVERT QUAND ON A MIS À JOUR -->
   <%#= params[:event].to_i == admin_event.id ? 'is-active is-visible' : '' %>

  <!-- drawer info admin event -->
  <%= render "pages/dashboard_drawers/drawer_info_admin_event", admin_event: admin_event, farm: farm %>
<% end %>

app/views/pages/dashboard_sections/_egg_count.html.erb
<div class="mt-4 dashboard-crop-plan-line-card green" id="tour-des-jardins">
  <div class="card-colored-top-part-fixed-color green">
    <a href="#" data-toggle="modal" data-target="#modal-new-egg-count-query">
      <div class="card-top-part-text"><%= link_to farm_poulettes_path(current_user.farm_id), class: "white" do %>
        La ponte cette semaine 🥚<% end %></div>
    </a>
  </div>
  <div class="card-bottom-part">
    <div class="card-bottom-part-text">
      <div class="mt-2 raisin">
        <% if @daily_egg_counts_this_week.empty? %>
          Vous n'avez encore rien renseigné 🙃
        <% end %>
        <div>
          <% @daily_egg_counts_this_week.each do |egg_count| %>
            <div class="list-item-block d-flex justify-content-between mt-2">
              <div class="mt-2">
                <%= egg_count.date.to_date.strftime('%-d') %> <%= I18n.t(:month_names)[egg_count.date.to_date.strftime('%b').to_sym] %>
              </div>
              <div class="mt-2">
                <%= egg_count.egg_count %> œufs pondus
              </div>
              <%= link_to farm_daily_egg_count_path(@farm, egg_count.id, start_date: params[:start_date]), method: :delete, data: { confirm: "T'es #{current_user.is_female? ? 'sûre' : 'sûr'} ? 🤨"} do %>
              <div class="round-button red">
                <i class="fas fa-times round-txt-button"></i>
              </div>
            <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-end card-bottom-section-with-icon" id="search-harvest">
      <a href="#" data-toggle="modal" data-target="#modal-new-egg-count-query">
        <div class="card-bottom-right-triangle green">
          <i class="fas fa-plus"></i>
        </div>
      </a>
    </div>

    <div class="modal fade" id="modal-new-egg-count-query" tabindex="-1" aria-labelledby="modal-new-egg-count-queryLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h2>Enregistrer la ponte du jour</h2>
          </div>
          <div class="modal-body">
            <%= simple_form_for [farm, @egg_count], url: farm_daily_egg_counts_path(@farm.id, start_date: params[:start_date]) do |f| %>
              <div class="flex-wrap d-flex justify-content-between">
                <div>
                  <h3>Date</h3>
                  <div><%= f.input :date, as: :string, label: false, input_html: { class: "datepickernotime fit-content search-input-target-date" } %></div>
                  <h3 class="mt-4">Alors, combien ?</h3>
                  <div><%= f.input :egg_count, as: :integer, label: false, class: "w-100" %></div>
                </div>
              </div>
              <div class="d-flex">
                <%= f.submit "Valider", class: "btn txt-button mt-4 mx-auto" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>