config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  resources :farms, only: [ :show ] do
    resources :calendrier, controller: 'events', only: [ :index, :edit, :update, :new, :create, :destroy ]
    post "events_multiple_update", to: 'events#events_multiple_update'

    resources :produits, controller: 'products', only: [ :index, :show, :edit, :update, :create, :new ]
    resources :daily_egg_counts, only: [ :index, :show, :edit, :update, :create, :new, :destroy ]
    resources :variets, controller: 'vegetable_variets', only: [ :edit, :update, :create, :new ]
    get "product_variets_multiple_new", to: 'products#product_variets_multiple_new'
    post "product_variets_multiple_create", to: 'products#product_variets_multiple_create'
    resources :plandeculture, controller: 'crop_plan_lines', only: [ :index, :update, :edit ]
    resources :crop_plan_line_events, only: [ :update ]
    resources :newsletter_subscribers, only: [ :index, :new, :create ]
    resources :crop_plan_line_user_events, only: [ :create, :update, :destroy ]
    resources :ventes, controller: 'sales', only: [ :index, :show ]
    resources :poulettes, controller: 'hen_actions', only: [ :index, :show, :new, :create, :destroy, :edit, :update ]
    resources :decisions, only: [ :index, :show, :new, :create, :destroy, :edit, :update ]
    resources :pointsdevente, controller: 'outlets', only: [ :index, :show, :new, :create, :edit, :update ] do
      resources :baskets, only: [ :new, :create ]
      resources :factures, controller: "invoices", only: [ :new, :create, :index, :show, :update, :destroy ]
      resources :paiements, controller: "payments", only: [ :new, :create, :index, :show, :update, :destroy ]
      resources :sales, only: [ :index, :show, :new, :create, :update, :destroy ] do
        resources :livraisons, controller: "delivery_slips", only: [ :new, :create, :index, :show, :update, :destroy ]
        resources :baskets, only: [ :index, :show, :update, :destroy ] do
          resources :basket_lines, only: [ :index, :show, :new, :update, :create, :destroy ]
        end
      end
    end
    resources :thebest, controller: 'users', only: [ :show ]
    resources :sales_lines, only: [ :index, :show, :new, :update, :create, :destroy ]
    get "last_prices_multiple_new", to: 'outlets#last_prices_multiple_new'
    post "last_prices_multiple_create", to: 'outlets#last_prices_multiple_create'
    resources :user_events, only: [ :create, :update, :destroy ]
    get 'dashboard', to: 'pages#dashboard'
  end
end

app/views/shared/_basket_buttons.html.erb
<% if sale.has_baskets? %>
  <%= link_to farm_pointsdevente_sale_baskets_path(@farm, outlet, sale) do %>
    <div class="round-button olive m-2">
      <%= image_tag "panier.png", alt: "panier", class: "round-img-button" %>
    </div>
  <% end %>
<% else %>
  <%= link_to new_farm_pointsdevente_basket_path(@farm, outlet, date: sale.date&.to_date) do %>
    <div class="round-button lightgrey m-2">
      <%= image_tag "panier.png", alt: "panier", class: "round-img-button" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_delivery_slip_buttons.html.erb
<% if sale.has_delivery_slip? && sale.delivery_slip.is_confirmed? %>
  <%= link_to farm_pointsdevente_sale_livraison_path(@farm, sale.outlet, sale, sale.delivery_slip, format: "pdf") do %>
    <div class="round-button olive %> m-2">
      <i class="far fa-file-alt round-txt-button"></i>
    </div>
  <% end %>
<% elsif sale.has_delivery_slip? %>
  <div class="dropdown show">
    <div class="round-button green m-2" id="dropdownDelivery<%= sale.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="far fa-file-alt round-txt-button"></i></div>
    <div class="dropdown-menu modal-position-center" aria-labelledby="dropdownDelivery<%= sale.id %>">
      <%= link_to farm_pointsdevente_sale_livraison_path(@farm, sale.outlet, sale, sale.delivery_slip, format: "pdf") do %>
        <div class="sales-line-bed-choice text-center raisin p-1 mb-2">Consulter</div>
      <% end %>
      <div class="sales-line-bed-choice text-center p-1"><%= link_to farm_pointsdevente_sale_livraison_path(@farm, sale.outlet, sale, sale.delivery_slip), method: :patch, class: "raisin" do %>Marquer comme envoyé ✔️<% end %></div>
    </div>
  </div>
<% else %>
  <%= link_to new_farm_pointsdevente_sale_livraison_path(@farm, sale.outlet, sale) do %>
    <div class="round-button lightgrey %> m-2">
      <i class="far fa-file-alt round-txt-button"></i>
    </div>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_invoice_buttons.html.erb
<% if sale.has_invoice? && sale.invoice.is_sent? %>
  <%= link_to farm_pointsdevente_facture_path(@farm, sale.outlet, sale.invoice, format: "pdf") do %>
    <div class="round-button no-pointer olive %> m-2">
      <%= image_tag "invoice.png", alt: "invoice", class: "round-img-button" %>
    </div>
  <% end %>
<% elsif sale.has_invoice? %>
  <div class="dropdown show">
    <div class="round-button green m-2" id="dropdownInvoice<%= sale.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= image_tag "invoice.png", alt: "invoice", class: "round-img-button" %></div>
    <div class="dropdown-menu modal-position-center" aria-labelledby="dropdownInvoice<%= sale.id %>">
      <%= link_to farm_pointsdevente_facture_path(@farm, sale.outlet, sale.invoice, format: "pdf") do %>
        <div class="sales-line-bed-choice text-center raisin p-1 mb-2">Consulter</div>
      <% end %>
      <div class="sales-line-bed-choice text-center p-1"><%= link_to farm_pointsdevente_facture_path(@farm, sale.outlet, sale.invoice), method: :patch, class: "raisin" do %>Marquer comme envoyée ✔️<% end %></div>
    </div>
  </div>
<% else %>
  <%= link_to new_farm_pointsdevente_facture_path(@farm, sale.outlet) do %>
    <div class="round-button lightgrey %> m-2">
      <%= image_tag "invoice.png", alt: "invoice", class: "round-img-button" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_main_navbar.html.erb
<nav id="sidebar" class="desktop_only">
  <div>
    <div>
      <%= link_to root_path do %>
        <%= image_tag "logo.png", class: "small-logo" %>
      <% end %>
    </div>
    <% if current_user.worker %>
      <ul class="list-unstyled sidebar-items">
        <li class="active sidebar-item align-middle">
          <%= link_to farm_dashboard_path(current_user.farm_id, start_date: Date.today.beginning_of_week) do %><i class="fas fa-clipboard-list sidebar-icon-item"></i><% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to farm_thebest_path(current_user.farm_id, current_user) do %>
          <i class="fas fa-user-circle sidebar-icon-item"></i>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to farm_path(current_user.farm_id) do %>
            <%= image_tag "greenhouse.png" %>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to farm_ventes_path(current_user.farm_id) do %>
            <i class="fas fa-euro-sign sidebar-icon-item"></i>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to farm_calendrier_index_path(current_user.farm_id) do %>
            <i class="fas fa-calendar-alt sidebar-icon-item"></i>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to farm_plandeculture_index_path(current_user.farm_id) do %>
            <i class="fas fa-seedling sidebar-icon-item"></i>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to farm_produits_path(current_user.farm_id) do %>
            <%= image_tag "carrot.png" %>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to farm_poulettes_path(current_user.farm_id) do %>
            <%= image_tag "hen.png" %>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to farm_decisions_path(current_user.farm_id) do %>
            <%= image_tag "decision.png" %>
          <% end %>
        </li>
      </ul>
    <% else %>
      <ul class="list-unstyled sidebar-items">
        <li class="active sidebar-item align-middle">
          <%= link_to farm_thebest_path(current_user.farm_id, current_user) do %>
          <i class="fas fa-user-circle sidebar-icon-item"></i>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to farm_ventes_path(current_user.farm_id) do %>
            <i class="fas fa-euro-sign sidebar-icon-item"></i>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to farm_plandeculture_index_path(current_user.farm_id) do %>
            <%= image_tag "shopping-cart.png" %>
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>

  <div>
    <%= link_to destroy_user_session_path, method: :delete, class: "logout-button-link" do %>
      <%= image_tag "deconnexion.png", class: "logout-button" %>
    <% end %>
  </div>
</nav>

<div class="mobile_only">
  <div id="bottom-navbar" >
    <%= link_to farm_dashboard_path(current_user.farm_id, start_date: Date.today.beginning_of_week) do %>
      <i class="fas fa-clipboard-list sidebar-icon-item"></i>
    <% end %>
    <%= link_to farm_thebest_path(current_user.farm_id, current_user) do %>
      <i class="fas fa-user-circle sidebar-icon-item"></i>
    <% end %>
    <%= link_to farm_path(current_user.farm_id) do %>
      <i class="fas fa-home sidebar-icon-item"></i>
    <% end %>
    <%= link_to farm_ventes_path(current_user.farm_id) do %>
      <i class="fas fa-euro-sign sidebar-icon-item"></i>
    <% end %>
    <%= link_to farm_produits_path(current_user.farm_id) do %>
      <i class="fas fa-carrot sidebar-icon-item"></i>
    <% end %>
    <%= link_to farm_poulettes_path(current_user.farm_id) do %>
      <%= image_tag "hen.png" %>
    <% end %>
  </div>
</div>

app/views/shared/_pages_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar">
  <div class="d-flex">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  </div>

  <div>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? && current_user.worker %>
        <li class="nav-item">
          <%= link_to farm_dashboard_path(current_user.farm_id, start_date: Date.today.beginning_of_week), class: "nav-link" do %><%= image_tag "connexion.png", alt: "connexion", class: "login-button" %><% end %>
        </li>
      <% elsif user_signed_in? %>
        <li class="nav-item">
          <%= link_to farm_thebest_path(current_user.farm_id, current_user), class: "nav-link" do %><%= image_tag "connexion.png", alt: "connexion", class: "login-button" %><% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %><%= image_tag "connexion.png", alt: "connexion", class: "login-button" %><% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_payment_buttons.html.erb
<% if sale.is_paid? %>
  <div class="dropdown show">
    <div class="round-button olive m-2" id="dropdownPaid<%= sale.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-euro-sign round-txt-button"></i>
    </div>
    <div class="dropdown-menu wide-modal-position-center" aria-labelledby="dropdownPaid<%= sale.id %>">
      <div class="text-center pl-1 pr-1" style="padding-top: 6px; padding-bottom: 12px;">
        Payé : <%= get_price_in_cents(sale.total_paid) %>
      </div>
    </div>
  </div>
<% else %>
  <div class="dropdown show">
    <div class="round-button red m-2" id="dropdownPayment<%= sale.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-euro-sign round-txt-button"></i>
    </div>
    <div class="dropdown-menu wide-modal-position-center" aria-labelledby="dropdownPayment<%= sale.id %>">
      <div class="text-center pl-1 pr-1 border-bottom-lightgrey" style="padding-top: 6px; padding-bottom: 12px;">Déjà payé : <%= get_price_in_cents(sale.amount_paid) %></div>
      <%= link_to farm_pointsdevente_paiements_path(@farm, outlet, sale_id: sale.id), method: :post do %>
        <div class="sales-line-bed-choice text-center raisin pl-1 pr-1" style="padding-top: 6px; padding-bottom: 6px">Marquer comme payé en intégralité  🎉</div>
      <% end %>
      <div class="sales-line-bed-choice justify-content-center d-flex">
        <div style="line-height: 36px" class="pr-2">Autre montant payé</div>
        <div class="d-flex">
          <%= form_tag farm_decisions_path(@farm), method: :patch, class: "search-input d-flex" do %>
            <%= text_field_tag :query, params[:query], class: "form-control h-30-px w-60-px br-none input-paid-amount" %>
            <button type="submit" class="btn confirm-button" id="submit">
              <div class="round-button olive mr-0"><i class="fas fa-check round-txt-button"></i></div>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>