config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  resources :farms, only: [ :show ] do
    resources :calendrier, controller: 'events', only: [ :index, :edit, :update, :new, :create, :destroy ]
    post "events_multiple_update", to: 'events#events_multiple_update'

    resources :produits, controller: 'products', only: [ :index, :show, :edit, :update, :create, :new ]
    resources :daily_egg_counts, only: [ :index, :show, :edit, :update, :create, :new, :destroy ]
    resources :variets, controller: 'vegetable_variets', only: [ :edit, :update, :create, :new ]
    get "product_variets_multiple_new", to: 'products#product_variets_multiple_new'
    post "product_variets_multiple_create", to: 'products#product_variets_multiple_create'
    resources :plandeculture, controller: 'crop_plan_lines', only: [ :index, :update, :edit ]
    resources :crop_plan_line_events, only: [ :update ]
    resources :newsletter_subscribers, only: [ :index, :new, :create ]
    resources :crop_plan_line_user_events, only: [ :create, :update, :destroy ]
    resources :ventes, controller: 'sales', only: [ :index, :show ]
    resources :poulettes, controller: 'hen_actions', only: [ :index, :show, :new, :create, :destroy, :edit, :update ]
    resources :decisions, only: [ :index, :show, :new, :create, :destroy, :edit, :update ]
    resources :pointsdevente, controller: 'outlets', only: [ :index, :show, :new, :create, :edit, :update ] do
      resources :baskets, only: [ :new, :create ]
      resources :factures, controller: "invoices", only: [ :new, :create, :index, :show, :update, :destroy ]
      resources :paiements, controller: "payments", only: [ :new, :create, :index, :show, :update, :destroy ]
      resources :sales, only: [ :index, :show, :new, :create, :update, :destroy ] do
        resources :livraisons, controller: "delivery_slips", only: [ :new, :create, :index, :show, :update, :destroy ]
        resources :baskets, only: [ :index, :show, :update, :destroy ] do
          resources :basket_lines, only: [ :index, :show, :new, :update, :create, :destroy ]
        end
      end
    end
    resources :thebest, controller: 'users', only: [ :show ]
    resources :sales_lines, only: [ :index, :show, :new, :update, :create, :destroy ]
    get "last_prices_multiple_new", to: 'outlets#last_prices_multiple_new'
    post "last_prices_multiple_create", to: 'outlets#last_prices_multiple_create'
    resources :user_events, only: [ :create, :update, :destroy ]
    get 'dashboard', to: 'pages#dashboard'
  end
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :outlet
  belongs_to :invoice, optional: true
  has_many :sales_lines
  has_many :baskets
  has_one :delivery_slip
  has_many :payments

  def has_comment?
    !self.comment.nil? && !self.comment.empty?
  end

  def has_baskets?
    !self.baskets.nil? && !self.baskets.empty?
  end

  def has_delivery_slip?
    !self.delivery_slip.nil?
  end

  def has_invoice?
    !self.invoice.nil?
  end


  def has_payments?
    (self.has_invoice? && !self.invoice.payments.nil? && !self.invoice.payments.empty?) || (!self.payments.nil? && !self.payments.empty?)
  end

  def amount_paid
    total_paid = 0
    if self.has_payments? && self.has_invoice?
      self.invoice.payments.each do |payment|
        total_paid += payment.paid_amount
      end
      return total_paid
    elsif self.has_payments?
      self.payments.each do |payment|
        total_paid += payment.paid_amount
      end
      return total_paid
    else
      total_paid
    end
  end

  def total_paid
    if self.is_paid?
      self.ttc_total
    end
  end

  def is_paid?
    total_paid = 0
    if self.has_invoice? && self.has_payments?
      self.invoice.payments.each do |payment|
        total_paid += payment.paid_amount
      end
      ht_total = self.invoice.ht_total.nil? ? 0 : self.invoice.ht_total
      total_paid >= ht_total
    elsif self.has_payments?
      self.payments.each do |payment|
        total_paid += payment.paid_amount
      end
      ht_total = self.ht_total.nil? ? 0 : self.ht_total
      total_paid >= ht_total
    else
      false
    end
  end

  def self.policy_class
    SalePolicy
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_farm, only: [:new, :create, :index, :update, :show]
  before_action :set_outlet, only: [:new, :create]
  before_action :set_sale, only: [:show, :update]

  def index
    @sales = @farm.sales
    authorize @sales
    @outlet_list = @farm.outlets.pluck(:full_name, :shortened_name)
    @farm.outlets.each { |o| @outlet_list.push(o.full_name[0..3]) }

    if params[:query].present?
      @query = params[:query]
      month_number = I18n.t(:month_numbers)[params[:query].to_sym]
      paid_not_paid_list = ["payé", "payée", "pay", "impayé", "impayée", "impay", "imp"]
      panier_list = ["paniers", "pan", "panier"]

      if month_number != nil
        sales_for_month(month_number)
      elsif paid_not_paid_list.include?(@query)
        paid_not_paid_sales(params[:query])
      elsif panier_list.include?(@query)
        panier_sales(params[:query])
      else
        outlet_sales(@query)
      end
    else
      @sales = @farm.sales.order("date DESC")
      @sale_count = @sales.length
    end
    @outlets = @farm.outlets
  end

  def show
    @sale = Sale.find(params[:id])
    authorize @sale

    # last_prices(@sale)

    @new_sales_line = SalesLine.new
    @sales_lines = @sale.sales_lines.order(:created_at)
    @beds = Bed.all.order(:full_name).pluck(:full_name, :id)
    @products = Product.where(farm_id: @farm.id).order(:slug).map { |product| [product.name.capitalize, product.id] }
  end

  def new
    @sale = Sale.new
    authorize @sale
  end

  def create
    date = params[:sale][:date]
    if params[:sale][:frequency] == ""
      @sale = Sale.new(date: Date.parse(date), outlet_id: @outlet.id, comment: params[:sale][:comment])
      authorize @sale
      if @sale.save
        flash[:notice] = "Vente du #{date.to_date.strftime('%-d')} #{I18n.t(:month_names)[date.to_date.strftime('%b').to_sym]} créée avec succès !"
        redirect_to farm_pointsdevente_sale_path(@farm, @sale.outlet, @sale)
      else
        flash[:alert] = "Il doit manquer quelques infos"
        render :new
      end
    elsif params[:sale][:frequency] == "Toutes les semaines"
      dates = [params[:sale][:first_date].to_date]
      last_added_date = params[:sale][:first_date].to_date
      last_date = params[:sale][:last_date].to_date
      while last_added_date < last_date
        new_date = last_added_date + 1.week
        last_added_date = new_date
        dates.push(new_date)
      end
      sales_added = 0
      dates.each do |date|
        @sale = Sale.create!(date: date, outlet_id: @outlet.id, comment: params[:sale][:comment])
        authorize @sale
        sales_added += 1
      end
      redirect_to farm_ventes_path(@farm)
      flash[:notice] = "#{sales_added} ventes créées avec succès !"
    elsif params[:sale][:frequency] == "Une semaine sur deux"
      dates = [params[:sale][:first_date].to_date]
      last_added_date = params[:sale][:first_date].to_date
      last_date = params[:sale][:last_date].to_date
      while last_added_date < last_date
        new_date = last_added_date + 2.week
        last_added_date = new_date
        if new_date < last_date
          dates.push(new_date)
        end
      end
      sales_added = 0
      dates.each do |date|
        @sale = Sale.create!(date: date, outlet_id: @outlet.id, comment: params[:sale][:comment])
        authorize @sale
        sales_added += 1
      end
      redirect_to farm_ventes_path(@farm)
      flash[:notice] = "#{sales_added} ventes créées avec succès !"
    end
    authorize @sale
  end

  def update
    if params[:add_comment]
      if @sale.update(comment: params[:sale][:comment])
        redirect_to farm_ventes_path(@farm)
        flash[:notice] = "Commentaire ajouté avec succès !"
      end
    end
    authorize @sale
  end


  private

  def set_farm
    @farm = Farm.find(params[:farm_id])
  end

  def set_outlet
    @outlet = Outlet.find(params[:pointsdevente_id])
  end

  def set_sale
    @sale = Sale.find(params[:id])
  end

  def sales_for_month(month)
    @sales = Sale.where('extract(month from date) = ?', month).order("date DESC")
    @sale_count = @sales.length
  end

  def paid_not_paid_sales(query)
    paid_list = ["payé", "payée", "pay",]
    not_paid_list = ["impayé", "impayée", "impay", "imp"]
    if not_paid_list.include?(query)
      @sales = Sale.all.select { |sale| !sale.is_paid? && sale.ttc_total != 0 }.sort_by(&:date).reverse!
      @sale_count = @sales.length
      @total_unpaid = @sales.map{|s| s.ttc_total}.sum
    elsif paid_list.include?(query)
      @sales = Sale.all.select { |sale| sale.is_paid? }.sort_by(&:date).reverse!
      @sale_count = @sales.length
    end
  end

  def panier_sales(query)
    @sales = Sale.all.select { |sale| sale.has_baskets? }.sort_by(&:date).reverse!
    @sale_count = @sales.length
  end

  def outlet_sales(query)
    sql_query = "full_name ILIKE :query"
    @sales = Outlet.where(sql_query, query: "%#{params[:query]}%").where(farm_id: current_user.farm_id).map(&:sales).flatten.sort_by(&:date).reverse!
    @sale_count = @sales.length
  end

  def last_prices(sale)
    @last_prices = {}
    products = Product.where(farm_id: @farm.id)
    products.each do |product|
      product_last_prices = []
      last_prices = LastPrice.all.where('product_id = ?', 1)
      last = last_prices.map do |last_price|
        ((last_price.amount[0].to_i)/100).to_s + " €/" + last_price.unit[0]
      end
    end
    @last_prices = LastPrice.all.group_by(&:product_id).each {|p, v| v.group_by(&:unit)}.transform_keys{|k| Product.find(k).name.capitalize}
    @last_prices.map{|k, v| @last_prices[k] = [v[0].amount, v[0].unit]}.to_json
  end

end

app/views/sales/_form.html.erb
<%= form_with model: sale, url: url, method: :post, local: true do |f| %>
  <div class="flex-wrap d-flex justify-content-between">
    <div class="w-48-desktop">
      <h3 class="mt-4">Vente unique ?</h3>
      <div class="simple-card">
        <h4>Date de la vente</h4>
        <%= f.date_field :date, :label => "Date" %>
        <div class="mt-4">
          <h4>Commentaire</h4>
          <%= f.text_area :comment, rows: "4", class: "w-100" %>
        </div>
      </div>
    </div>
    <div  class="w-48-desktop">
      <h3 class="mt-4">Ou vente récurrente ?</h3>
      <div class="simple-card">
        <div class="d-sm-flex justify-content-between">
          <div>
            <h4>Date de la première vente</h4>
            <%= f.date_field :first_date, :label => "Date" %>
          </div>
          <div>
          <h4 class="pt-4 pt-sm-0">Date de la dernière vente</h4>
            <%= f.date_field :last_date, :label => "Date" %>
          </div>
        </div>
        <div class="mt-4">
          <h4>Fréquence</h4>
          <%= f.select :frequency, ["", "Toutes les semaines", "Une semaine sur deux"], class: "w-100" %>
        </div>
        <div class="mt-4">
          <h4>Commentaire</h4>
          <h5><i class="fas fa-info-circle"></i> Ce commentaire sera présent sur toutes les ventes de la période</h5>
          <%= f.text_area :recurrent_comment, rows: "4", class: "w-100" %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex">
    <%= f.submit "Valider", class: "btn txt-button mt-4 mx-auto" %>
  </div>
<% end %>

app/views/sales/_sale_add_comment_drawer.html.erb
<section class="drawer" id="drawer-sale-add-comment-<%= sale.id %>" data-drawer-target>
  <div class="drawer__overlay" data-drawer-close tabindex="-1"></div>
  <div class="drawer__wrapper">
    <div class="drawer__header">
      <div class="d-flex justify-content-between">
        <div class="drawer__title">
          <div>
            <h2>Nouveau commentaire</h2>
          </div>
          <div class="drawer-title-second-line">Vente <%= sale.outlet.full_name %> du <%= sale.date.to_date.strftime('%-d') %> <%= I18n.t(:month_names)[sale.date.to_date.strftime('%b').to_sym] %></div>
        </div>
        <button class="drawer__close" data-drawer-close aria-label="Fermer le drawer">
          <i class="fas fa-times"></i>
        </button>
      </div>
    </div>
    <div class="drawer__content drawer-content-with-bottom-buttons">
      <div>
        <%= form_with model: sale, url: farm_pointsdevente_sale_path(farm, outlet, sale, add_comment: true), method: :patch, local: true do |form| %>
        <h4 class="mt-4">Commentaire</h4>
        <%= form.text_area :comment, class: "mt-2 w-100", rows: "4" %>
      </div>
      <div class="drawer-edit-bottom-buttons px-sm-4">
        <div><%= form.submit value: "Valider", class: "btn txt-button-background olive mt-2", 'data-disable-with': "..." %></div>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/sales/_sale_comment_drawer.html.erb
<section class="drawer" id="drawer-sale-comment-<%= sale.id %>" data-drawer-target>
  <div class="drawer__overlay" data-drawer-close tabindex="-1"></div>
  <div class="drawer__wrapper">
    <div class="drawer__header">
      <div class="d-flex justify-content-between">
        <div class="drawer__title">
          <div>
            <h2>Vente <%= sale.outlet.full_name %> du <%= sale.date.to_date.strftime('%-d') %> <%= I18n.t(:month_names)[sale.date.to_date.strftime('%b').to_sym] %></h2>
          </div>
        </div>
        <button class="drawer__close" data-drawer-close aria-label="Close Drawer">
          <i class="fas fa-times"></i>
        </button>
      </div>
    </div>
    <div class="drawer__content">
      <h4 class="pt-3">Commentaire</h4>
      <% if sale.has_comment? %>
        <p>
          <%= sale.comment.capitalize %>
        <p>
      <% else %>
        <p>Pas de commentaire. Si tu as des choses à dire, clique <span class="pointer orange" data-drawer-trigger aria-controls="drawer-sale-add-comment-<%= sale.id %>" aria-expanded="false">LÀ !</span></p>
      <% end %>
    </div>
  </div>
</section>

app/views/sales/index.html.erb
<div class="container custom-container">
   <div class="page-header non-scrolled-page-header scrollable-page-header d-flex justify-content-between">
      <h2>Les ventes <span class="ml-2"></span></h2>
      <div class="d-flex">
        <div class="pr-38 d-flex fs-24-16" style="margin-top: -4px">
          <span class="fs-14 pr-2 pl-sm-2 pt-sm-2" style="margin-top: 0.1em"><%= get_price_in_cents(@farm.ht_turnover) %></span><span class="pr-2">|</span><%= get_price_in_cents(@farm.ttc_turnover) %>
        </div>
        <div class="pr-38 d-flex">
          <div class="dropdown show">
            <div class="round-button green" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-plus round-txt-button"></i></div>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <div class="dropdown-farm-create dropleft"><a class="dropdown-item dropdown-toggle" href="#">Créer une vente</a>
                <ul class="submenu dropdown-menu">
                  <% @outlets.each do |outlet| %>
                    <li><%= link_to new_farm_pointsdevente_sale_path(@farm, outlet), class: 'dropdown-item' do %><%= outlet.full_name %><% end %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <div class="page-content">
  </div>

  <div>
    <div class="progress">
      <div class="progress-bar" role="progressbar" style="width: <%= percentage(@farm.ttc_turnover, @farm.estimated_ttc_turnover).round %>%" aria-valuenow="<%= percentage(@farm.ttc_turnover, @farm.estimated_ttc_turnover) %>" aria-valuemin="0" aria-valuemax="100"><%= percentage(@farm.ttc_turnover, @farm.estimated_ttc_turnover).round %> %</div>
    </div>


    <div class="search-form mt-4">
      <%= form_tag farm_ventes_path(@farm.id), method: :get, class: "search-input" do %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Chercher une vente" %>
        <button type="submit" class="btn search-button" id="submit">
          <i class="fas fa-search"></i>
        </button>
      <% end %>
    </div>

    <div class="d-flex justify-content-end">
      <button type="button" class="btn green pr-0" data-toggle="modal" data-target="#exampleModalLong">
        <i class="fas fa-info-circle round-txt-button"></i>
      </button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-body">
            La recherche peut se faire selon ces différents critères :
            <ul>
              <li>Nom du point de vente</li>
              <li>Mois</li>
              <li>Payée / Impayée</li>
              <li>Paniers</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div>
      <% if @total_unpaid != 0 && !@total_unpaid.nil? %>
        <div><h3><%= @sale_count %> <%= pluralize(@sale_count, "vente impayée", "ventes impayées") %></h3>
        </div>
        <div>
          ⚠️ Reste à percevoir : <%= get_price_in_cents(@total_unpaid) %>
        </div>
        <% else %>
        <div><h3><%= @sale_count %> <%= pluralize(@sale_count, "vente", "ventes") %> <%= @query ? "(pour la recherche : #{@query})" :  "" %></h3>
        </div>
      <% end %>
    </div>
    <div class="my-4 desktop_only">
      <% @sales.each do |sale| %>
        <div class="d-flex justify-content-between list-item-block my-2">
          <div class="card-list-item-left-block">
            <div class="align-self-center pr-4" style="width: 130px">
              <p><%= sale.date.to_date.strftime('%-d') %> <%= I18n.t(:month_names)[sale.date.to_date.strftime('%b').to_sym] %></p>
            </div>
              <h4 class="mb-0 align-self-center fw-500"><%= link_to farm_pointsdevente_path(@farm, sale.outlet), class: "green-hover" do %><%= sale.outlet.full_name %><% end %></h4>
          </div>
          <div class="d-flex justify-content-between card-list-item-round-button-block">
            <div class="d-flex desktop_only">
              <%= link_to farm_pointsdevente_sale_path(@farm, sale.outlet, sale) do %>
                <div class="round-button green m-2">
                  <i class="fas fa-search round-txt-button"></i>
                </div>
              <% end %>
              <div class="round-button <%= sale.has_comment? ? 'green' : 'lightgrey' %> m-2" data-drawer-trigger aria-controls="drawer-sale-comment-<%= sale.id %>" aria-expanded="false">
                <i class="fas fa-comment round-txt-button"></i>
              </div>
              <%= render "shared/basket_buttons", sale: sale, outlet: sale.outlet %>
              <%= render "shared/delivery_slip_buttons", sale: sale %>
              <%= render "shared/invoice_buttons", sale: sale %>
              <%= render "shared/payment_buttons", sale: sale, outlet: sale.outlet %>

            </div>
            <div class="align-self-center" style="text-align-last: right; min-width: 80px;">
              <div class="d-flex justify-content-end" style="width: 200px"><span style="padding-top: 3px" class="pr-2 lightgrey"><%= get_price_in_cents(sale.ht_total) %></span>|<h4 class="mb-0 align-self-center fw-500 pl-2"><%= get_price_in_cents(sale.ttc_total) %></h4></div>
            </div>
          </div>
        </div>
        <%= render "sale_comment_drawer", sale: sale %>
        <%= render "sale_add_comment_drawer", farm: @farm, outlet: sale.outlet, sale: sale %>
      <% end %>
    </div>
    <div class="mobile_only">
      <% @sales.each do |sale| %>
        <div id="carouselSalesIndex" class="carousel-sales carousel slide" data-ride="carousel" data-interval="false">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="d-flex justify-content-between list-item-block my-2">
                <div class="card-list-item-left-block w-75">
                  <div class="align-self-center pr-2">
                    <p><%= sale.date.to_date.strftime('%-d/%m') %></p>
                  </div>
                    <h4 class="mb-0 align-self-center fw-500"><%= link_to farm_pointsdevente_path(@farm, sale.outlet), class: "green-hover" do %><%= sale.outlet.full_name %><% end %></h4>
                </div>
                <div class="d-flex justify-content-between card-list-item-round-button-block">
                  <div class="d-flex desktop_only">
                    <div class="round-button green m-2">
                      <i class="fas fa-search round-txt-button"></i>
                    </div>
                    <% if sale.has_baskets? %>
                      <%= link_to farm_pointsdevente_sale_baskets_path(@farm, sale.outlet, sale) do %>
                        <div class="round-button olive m-2">
                          <%= image_tag "panier.png", alt: "panier", class: "round-img-button" %>
                        </div>
                      <% end %>
                    <% else %>
                      <%= link_to new_farm_pointsdevente_basket_path(@farm, sale.outlet, date: sale.date&.to_date) do %>
                        <div class="round-button lightgrey m-2">
                          <%= image_tag "panier.png", alt: "panier", class: "round-img-button" %>
                        </div>
                      <% end %>
                    <% end %>
                    <div class="round-button red m-2">
                      <i class="fas fa-euro-sign round-txt-button"></i>
                    </div>
                    <div class="round-button red m-2">
                      <i class="far fa-file-alt round-txt-button"></i>
                    </div>
                  </div>
                  <div class="align-self-center">
                    <h4 class="mb-0 align-self-center fw-500"><%= get_price_in_cents(sale.ttc_total) %></h4>
                  </div>
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <div class="d-flex justify-content-between box-shadow-lightgrey my-4">
                <div class="d-flex mobile_only w-100 justify-content-center">
                  <div class="px-2">
                    <div class="round-button <%= sale.has_comment? ? 'green' : 'lightgrey' %> m-2" data-drawer-trigger aria-controls="drawer-sale-comment-<%= sale.id %>" aria-expanded="false">
                      <i class="fas fa-comment round-txt-button"></i>
                    </div>
                    <div class="round-button olive m-2">
                      <%= image_tag "panier.png", alt: "panier", class: "round-img-button" %>
                    </div>
                  </div>
                  <div class="px-2">
                    <div class="round-button green m-2">
                      <i class="fas fa-search round-txt-button"></i>
                    </div>
                  </div>
                  <div class="px-2">
                    <div class="round-button red m-2">
                      <i class="fas fa-euro-sign round-txt-button"></i>
                    </div>
                  </div>
                  <div class="px-2">
                    <div class="round-button red m-2">
                      <i class="far fa-file-alt round-txt-button"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <%= render "sale_comment_drawer", sale: sale %>
        <%= render "sale_add_comment_drawer", farm: @farm, outlet: sale.outlet, sale: sale %>

      <% end %>
    </div>

  </div>
</div>

app/views/sales/new.html.erb
<div class="container custom-container" style="overflow: auto;">
  <div class="page-header non-scrolled-page-header scrollable-page-header d-block">
    <h2 class="mb-0">Créer une vente pour <%= @outlet.full_name %></h2>
  </div>

  <div class="page-content">
  </div>
  <div class="container">
    <%= render 'form', farm: @farm, sale: @sale, outlet: @outlet, url: farm_pointsdevente_sales_path(@farm.id, @outlet.id, @sale.id) %>
  </div>
</div>